project:
  type: website

website:
  title: "Documentación del Proyecto RFM"
  sidebar:
    - title: "Resumen"
      style: "docked"
      contents:
        - href: index.qmd
          text: "Inicio"
        - href: intro.qmd
          text: "1. Introducción"
    - title: "Fases CRISP-DM"
      contents:
        - href: data_understanding.qmd
          text: "2. Entendimiento de Datos"
        - href: modeling.qmd
          text: "3. Modelado"
        - href: evaluation.qmd
          text: "4. Evaluación"
    - title: "Acerca de"
      contents:
        - href: about.qmd
          text: "Sobre el Proyecto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



